@localhost = localhost:4004/odata/v4/my
@id = 521d6814-9a1d-4c23-bfac-314d2d2c0e33
@custumer_Id = 53649126-4eb6-4dfd-9fbc-34169fffc3ec
@products_Id1 = 12195674-d9c9-4582-9aa2-2988724246d4

@products_Id2 = 12195671-1da6-4301-892d-c9165bd96088
GET http://{{localhost}}/SalesOrderHeaders?$expand=itens
Content-Type: application/json

###


POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json
Authorization: Basic kaique:Kaique@123

{
    "id": "{{id}}",
    "customer_id":"{{custumer_Id}}",
    "totalAmount": 30.5,
    "items": [
        {
            "id": "659d284e-a71c-4089-8999-e0197fd3d2a2",
            "header_id": "{{id}}",
            "product_id": "{{products_Id1}}",
            "quantiti": 10,
            "price": 20.99
        },

        {
            "id": "24cd7774-2ea1-4900-b537-6e069ad25225",
            "header_id": "{{id}}",
            "product_id": "{{products_Id1}}",
            "quantiti": 5,
            "price": 100000
        }
        ]

}

###


DELETE http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

{
    "id": "{{id}}"
}

###

PUT http://{{localhost}}/SalesOrderHeaders("id"=c7fd1cd3-bd65-4d27-8ca0-5cbdea4d0ccc")
Content-Type: application/json

###

// Filtro que busca totalAmount maior ou igual a 2000000
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount ge 2000000
Content-Type: application/json

###

// Filtro que busca totalAmount menor ou igual a 2000000
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount le 2000000
Content-Type: application/json

###

// Expandindo items em SalesOrderHeaders, expandindo customers e expandindo product em items
GET http://{{localhost}}/SalesOrderHeaders?$expand=items($expand=product),customer
Content-Type: application/json

###

// Selecionando somente o customer e id de SalesOrderHeader, expandindo o customer
GET http://{{localhost}}/SalesOrderHeaders?$select=id,customer&$expand=customer
Content-Type: application/json

###

// Descobrindo a quantidade de registro 
GET http://{{localhost}}/SalesOrderHeaders/$count
Content-Type: application/json

###

// Paginando os registros
GET http://{{localhost}}/SalesOrderHeaders?$skip=2&$top=3
Content-Type: application/json

###

// Pesquisando com o $search
GET http://{{localhost}}/SalesOrderHeaders?$search=eqx2i
Content-Type: application/json

###

// Ordenando dados 
GET http://{{localhost}}/Customers?$orderby=id desc
Content-Type: application/json
