@localhoast = localhost:4004/odata/v4/my
@id = 521d6814-9a1d-4c23-bfac-314d2d2c0e33
@custumer_Id = 53649126-4eb6-4dfd-9fbc-34169fffc3ec
@products_Id1 = 26147881-0b14-4733-92fb-dfd3558c6965

@products_Id2 = 12195671-1da6-4301-892d-c9165bd96088
GET http://{{localhoast}}/SalesOrderHeader?$expand=itens
Content-Type: application/json

###


POST http://{{localhoast}}/SalesOrderHeader
Content-Type: application/json

{
    "id": "{{id}}",
    "customer_id":"{{custumer_Id}}", 
    "itens": [
        {
            "id": "659d284e-a71c-4089-8999-e0197fd3d2a2",
            "header_id": "{{id}}",
            "product_id": "{{products_Id1}}",
            "quantiti": 10,
            "price": 20.99
        },

        {
            "id": "24cd7774-2ea1-4900-b537-6e069ad25225",
            "header_id": "{{id}}",
            "product_id": "{{products_Id2}}",
            "quantiti": 4,
            "price": 15.99
        }
        ]

}

###


DELETE http://{{localhoast}}/SalesOrderHeader(id={{id}})
Content-Type: application/json

{
    "id": "{{id}}"
}

###

PUT http://{{localhoast}}/SalesOrderHeader("id"=c7fd1cd3-bd65-4d27-8ca0-5cbdea4d0ccc")
Content-Type: application/json

###

// Filtro que busca totalAmount maior ou igual a 2000000
GET http://{{localhoast}}/SalesOrderHeader?$filter=totalAmount ge 2000000
Content-Type: application/json

###

// Filtro que busca totalAmount menor ou igual a 2000000
GET http://{{localhoast}}/SalesOrderHeader?$filter=totalAmount le 2000000
Content-Type: application/json

###

// Expandindo itens em SalesOrderHeader, expandindo custumers e expandindo product em itens
GET http://{{localhoast}}/SalesOrderHeader?$expand=itens($expand=product),customer
Content-Type: application/json

###

// Selecionando somente o customer e id de SalesOrderHeader, expandindo o customer
GET http://{{localhoast}}/SalesOrderHeader?$select=id,customer&$expand=customer
Content-Type: application/json

###

// Descobrindo a quantidade de registro 
GET http://{{localhoast}}/SalesOrderHeader/$count
Content-Type: application/json

###

// Paginando os registros
GET http://{{localhoast}}/SalesOrderHeader?$skip=2&$top=3
Content-Type: application/json

###

// Pesquisando com o $search
GET http://{{localhoast}}/SalesOrderHeader?$search=eqx2i
Content-Type: application/json

###

// Ordenando dados 
GET http://{{localhoast}}/Customers?$orderby=id desc
Content-Type: application/json
